### ISSUE TITLE
Cut 3d object feature in old-sculptgl Branch

### ISSUE THREAD

**Issue by xyzdcgan** [stephomi/sculptgl#90]
Hello, @stephomi 

How are you..?

I was looking to the old-sculptgl (SketchFab) branch and found CUT 3d object feature, but it is not working properly or i was not able to identify how it work?

Can you please let me know how that feature exactly works?, and is this feature available in master branch. (SculptGL) ? 

Thanks  @stephomi

**Comment by stephomi** [comment]
I just fixed it.
it's very old and I don't think it's robust though.

**Comment by stephomi** [comment]
Similarly to adaptive topology, the feature isn't on sculptgl though.

**Comment by xyzdcgan** [comment]
Yes, Thanks @stephomi it is solved in sketchfab, we are trying to add cut feature latest code. Thanks for Help.

**Comment by xyzdcgan** [comment]
Hello @stephomi , I tried to add the cut feature in SCULPT-GL. But somehow it is still not working. Can you please give us any idea to integrate that in SCULPT-GL. 

Thanks @stephomi
